/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  cp: [
    {
      type: 'autogenerated',
      dirName: 'cp',
    },
  ],
  cpp: [
    {
      type: 'autogenerated',
      dirName: 'cpp',
    },
  ],
  dip: [
    {
      type: 'autogenerated',
      dirName: 'dip',
    },
  ],
  dl: [
    {
      type: 'autogenerated',
      dirName: 'dl',
    },
  ],
  cloud: [
    {
      type: 'autogenerated',
      dirName: 'cloud',
    },
  ]
};
