module.exports = {
  cp: [
    {
      type: 'autogenerated',
      dirName: 'cp',
    },
  ],
  dip: [
    {
      type: 'autogenerated',
      dirName: 'dip',
    },
  ],
  dl: [
    {
      type: 'autogenerated',
      dirName: 'dl',
    },
  ]
};